# video input
input     : "../demo/yolo_test.mp4"
win_input : "..\\demo\\yolo_test.mp4"

# network config for yolo
net         : "yolo4tiny_fp32.rt"
ntype       : 'y'
n_classes   : 80
n_batch     : 1
conf_thresh : 0.3

# network config for mobile net
# net         : "mobilenetv2ssd_fp32.rt"
# ntype       : 'm'
# n_classes   : 80
# n_batch     : 1
# conf_thresh : 0.3

# demo config
show  : true
save  : true
